### ISSUE TITLE
Courses Created List

### ISSUE THREAD

**Issue by srmor** [NJIT-CLASS/backend#15]
We need an endpoint that gives back a list of the course IDs of the courses that a instructor has created.

Method: `GET`
Query Parameters:
- `instructor ID`

**Comment by cesarl88** [comment]
/getCourseCreated/:instructorID
{
  "Error": false,
  "Courses": [
    {
      "CourseID": 1,
      "Number": "CS-100",
      "Title": "Intro to Computer Science",
      "OrganizationID": 1,
      "CreatorID": 1
    },
    {
      "CourseID": 2,
      "Number": "CS-113",
      "Title": "Computer Science A",
      "OrganizationID": 1,
      "CreatorID": 1
    },
    {
      "CourseID": 3,
      "Number": "CS-114",
      "Title": "Computer Science B",
      "OrganizationID": 1,
      "CreatorID": 1
    },
    {
      "CourseID": 4,
      "Number": "12345",
      "Title": "TitleName",
      "OrganizationID": null,
      "CreatorID": 1
    }
  ]
}
