### ISSUE TITLE
Endpoint to deal with a user's admin status

### ISSUE THREAD

**Issue by srmor** [NJIT-CLASS/backend#17]
## 1. Make a user an admin

Method: `PUT`
Body (JSON):
- `user ID`

Response:
- status code `401` if the user doesn't exist
- status code `200` if they were successfully made an admin
## 2. Make a user not an admin

Method: `PUT`
Body (JSON):
- `user ID`
- `password`

Response:
- status code `401` if the user's password is invalid or the user is not valid
- status code `200` if the user's admin status was successfully changed

**Comment by cesarl88** [comment]
Implemented and tested in the test server
