### ISSUE TITLE
User Change Endpoints Status Codes

### ISSUE THREAD

**Issue by srmor** [NJIT-CLASS/backend#18]
- [ ] `PUT` `/update/password` needs to have a status code of `401` if the old password is not valid so the user's password wasn't changed.
- [ ] `PUT` `/update/email` needs to have a status code of `401` if the old password is not valid so the user's password wasn't changed.

**Comment by hfb7** [comment]
@srmor I was looking at this issue and it seems to be done. Please let me know what is wrong with it so I can take care of it or  please confirm if it is working.

**Comment by srmor** [comment]
Yes it does look like it's fixed. Thanks!
