### ISSUE TITLE
User Management Endpoints

### ISSUE THREAD

**Issue by srmor** [NJIT-CLASS/backend#2]
We need some endpoints for a user to edit their credentials. See the spec below:
### 1. Change a user's password

Method: `POST`
Body (JSON):
- `user ID`
- `current password`
- `new password`

Response:
- status code `401` if the current password is invalid
- status code `200` if the password was successfully changed
### 2. Change a user's email

Method: `POST`
Body (JSON):
- `user ID`
- `new email`
- `current password`

Response:
- status code `401` if the current password is invalid
- send back the new email if successfully changed (JSON)
### 3. Change a user's name

Method: `POST`
Body (JSON):
- `user ID`
- `first name`
- `last name`

Response:
- status code `400` if not successful for some reason
- send back the new first and last name if successfully changed (JSON)

**Comment by cga101** [comment]
Implemented yesterday with basic database schema.

**Comment by srmor** [comment]
Thanks @cga101! Two things. It looks like the endpoints should do what they are supposed to do, but since you made all three endpoints be `/api/update` only one is hit. It would probably be best if you changed them to be like `/api/update/password`, `/api/update/name`, `/api/update/email` or something like that. Let me know if that doesn't make sense.

Also for reference (and consistency) you can set status codes in Node with `res.status`. For example this line https://github.com/NJIT-CLASS/backend/blob/master/REST.js#L20 would be better like `res.status(401)`. That way it's simpler and that uses the actual HTTP status code header instead of sending JSON.

**Comment by cga101** [comment]
I actually didn't know about the status, thanks! 

And for some reason I totally thought that would work with a form lol. Changes made and committed.

**Comment by srmor** [comment]
Great thanks! Sorry I said the wrong thing. It should be `res.status(401).end()`. Right now the requests just timeout because the response isn't sent.

**Comment by cga101** [comment]
Appended .end() to the status codes.

**Comment by srmor** [comment]
Thanks @cga101!

**Comment by srmor** [comment]
This line https://github.com/NJIT-CLASS/backend/blob/master/REST.js#L37 is erroring when it is successful. I think it's because `UPDATE` doesn't return the row it updated (not sure). This is the stack trace:

```
TypeError: Cannot read property 'EmailAddress' of undefined
    at Query._callback (/home/app/backend/REST.js:38:29)
    at Query.Sequence.end (/home/app/backend/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Query._handleFinalResultPacket (/home/app/backend/node_modules/mysql/lib/protocol/sequences/Query.js:144:8)
    at Query.OkPacket (/home/app/backend/node_modules/mysql/lib/protocol/sequences/Query.js:78:10)
    at Protocol._parsePacket (/home/app/backend/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/home/app/backend/node_modules/mysql/lib/protocol/Parser.js:73:12)
    at Protocol.write (/home/app/backend/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/home/app/backend/node_modules/mysql/lib/Connection.js:96:28)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
```
