### ISSUE TITLE
Get Section Needs to return the section members

### ISSUE THREAD

**Issue by srmor** [NJIT-CLASS/backend#20]
Currently `/course/getsection/:sectionId` only returns the section details, but none of the users in the section. It needs to return a list of the users in the section as well.

**Comment by hfb7** [comment]
Here is the output of this endpoint:

{
  "result": [
    {
      "Name": "Section 1",
      "Description": "Non-Honors"
    }
  ],
  "UserSection": [
    {
      "UserID": 1,
      "UserRole": "Student"
    },
    {
      "UserID": 2,
      "UserRole": "Student"
    },
    {
      "UserID": 3,
      "UserRole": "Student"
    },
    {
      "UserID": 3,
      "UserRole": "Student"
    }
  ]
}

Please confirm is that what you need or if it is missing something.

**Comment by cga101** [comment]
Hirra said it's working.
