### ISSUE TITLE
Get semester IDs for a course

### ISSUE THREAD

**Issue by srmor** [NJIT-CLASS/backend#23]
Is `GET` `/course/:courseID` the way to get information about a course? If so it does not contain the course section IDs for that course. Could you possibly put those in there?

**Comment by cesarl88** [comment]
@srmor CourseID has been added to the response 
Please test it on your side. Here is the response I have.
test:
{
  "Error": false,
  "Message": "Success",
  "Course": [
    {
      "CourseID": 1,
      "Number": "CS-100",
      "Title": "Intro to Computer Science"
    }
  ],
  "Sections": [
    {
      "SectionID": 1,
      "SemesterID": 1,
      "CourseID": 1,
      "Name": "Section 1",
      "StartDate": "2016-01-01T00:00:00.000Z",
      "EndDate": "2016-05-01T00:00:00.000Z",
      "Description": "Non-Honors"
    },
    {
      "SectionID": 3,
      "SemesterID": 1,
      "CourseID": 1,
      "Name": "Section 3",
      "StartDate": "2016-01-01T00:00:00.000Z",
      "EndDate": "2016-05-01T00:00:00.000Z",
      "Description": "Tesing update Honors"
    }
  ]
}
