### ISSUE TITLE
General User Endpoint

### ISSUE THREAD

**Issue by srmor** [NJIT-CLASS/backend#3]
We need an API endpoint to generally get user information according to the spec below:

Method: `GET`
Query Parameters:
- `user id`

Response (JSON):
- `email address`
- `first name`
- `last name`
- `user type`

**Comment by srmor** [comment]
Currently this does not work because the userid is taken from the body instead of the querystring (since it's a get request and cannot have a body)  https://github.com/NJIT-CLASS/backend/blob/master/REST.js#L64

**Comment by cesarl88** [comment]
Ok. I noticed you made the changes. 
I had very similar as it is right now, but I changed it for some reason. 
My bad.

Feel free next time to let me know any issue so I can fix it.
