### ISSUE TITLE
Semester endpoints

### ISSUE THREAD

**Issue by srmor** [NJIT-CLASS/backend#4]
We need three endpoints to deal with semesters.
## 1. Create a semester

Method: `POST`
Body (JSON):
- `semester name`
- `start date`
- `end date`

Response:
- return the new `semester ID`
## 2. Get a semester's details

Method: `GET`
Query Parameters:
- `semester ID`

Response:
- `semester ID`,
- `semester name`
- `start date`
- `end date`
## 3. Get a list of all possible semester options

Method: `GET`

Response:
- list of `semester objects` (semester ID, semester name, start date, end date)

**Comment by cga101** [comment]
I think this is due next Thursday(?). 

Will we have some time to sit down and talk about the DB design? Or should we handle that ourselves?

**Comment by cga101** [comment]
Temporarily closing this, as we'll be doing testing tonight.

Also doesn't include Issue 9 changes, which will be last to complete.
