### ISSUE TITLE
Course creation and editing endpoints

### ISSUE THREAD

**Issue by srmor** [NJIT-CLASS/backend#5]
We need eight endpoints to handle course creation and editing.
## 1. Create a course

Method: `POST`
Body (JSON):
- `course number`
- `course name`
- `course owner id` (user id)

Response:
- return the new `course ID`
## 2. Create a course section

Method: `POST`
Body (JSON):
- `course id`
- `semester id`
- `section name`
- `section description`

Response:
- returns the new `course section ID`
## 3. Add a user to a section

Method: `POST`
Body (JSON):
- `email`
- `course id`
- `course section id`
  ` `relationship to the section` (`student` or `instructor`)

Response:
- returns the `user ID` (creates the user if they do not already exist)
## 4. Get a course

Method: `GET`
Query Parameters (JSON):
- `course ID`

Response:
- `course number`,
- `course name`
- `course creator ID`
## 5. Get a course section

Method: `GET`
Query Parameters (JSON):
- `course section ID`

Response:
- `section name`,
- `section description`
- `list of users` in the section and they're relationship to the section (student/instructor)
## 6. Update a course

Method: `PUT`
Body (JSON):
- `course ID`
- `course name`
- `course number`
- `course creator id`

Response:
- returns a 200 if it's successful
## 7. Update a course section

Method: `PUT`
Body (JSON):
- `course section ID`
- `section name`
- `section description`
- `semester id`

Response:
- returns a 200 if it's successful
## 8. Remove a user from a section

Method: `DELETE`
Body (JSON):
- `course section id`
- `user id`

Response
- returns a 200 if the the user is successfully removed from the section

**Comment by srmor** [comment]
The create course endpoint: https://github.com/NJIT-CLASS/backend/blob/master/REST.js#L276 uses a database field that doesn't exist (`Tittle` in table `Course`) @cesarl88 .

**Comment by cga101** [comment]
5.3 will finish making a new user after the password reset table is complete (they'll share the same has function for a temp password).

The rest are going to be tested tonight, my postman isn't working for some reason. Also saving Issue 9 changes for last.
