### ISSUE TITLE
Add admin field to user

### ISSUE THREAD

**Issue by srmor** [NJIT-CLASS/backend#7]
Add an admin field to User's in the database and return whether the user is an admin or not on the `/generalUser` endpoint.

**Comment by cga101** [comment]
Added a set in Class-Backend table that has options : 'User', 'Professor', and 'Admin'

Updated general endpoint to provide the UserType, let me know if you want the options to change.

Might have to discuss moving the Admin to a join or JSON to keep users who are only admins for one section separate, for now this should work for testing.

**Comment by srmor** [comment]
Ok great. Admins are admins for the whole system - not just a single section.
