### ISSUE TITLE
Endpoints to reset a user's password

### ISSUE THREAD

**Issue by srmor** [NJIT-CLASS/backend#8]
Create a table to handle holding current password reset requests and three endpoints to receive requests and handle password reseting
## 1. Create a hash corresponding that is attached to a user ID that represents a password reset request

Method: `POST`
Body (JSON):
- `email`

Response:
- 401 if the email is invalid
- 200 if valid email and password reset request created
## 2. Get a password reset request hash details

Method: `GET`
Query Parameters:
- `password request hash`

Response:
- corresponding `user ID` if valid reset request
- 404 if not a valid reset request
## 3. Reset a password for the user with a corresponding reset request

Method: `POST`
Body (JSON):
- `reset request hash`
- `new password`

Response:
- 401 if not successful
- 200 if password reset for corresponding user

**Comment by cga101** [comment]
Cesar Implemented 8.1-8.3. 

We're currently returning the hash code in the JSON, will be moving into sending an email out soon (updating with a new issue).
