### ISSUE TITLE
Broken Endpoints

### ISSUE THREAD

**Issue by srmor** [NJIT-CLASS/backend#9]
- [x] `PUT` `/update/password`
- [x] `PUT` `/update/email`
- [x] `GET` `/generalUser/:userid`
- [x] `POST` `/login`
- [x] `POST` `/CreateCourse` : tries to set a column (Tittle) that doesn’t exist
- [x] `POST` `/CreateSemester` : 

Why does it create it with start and end dates that are one day earlier?

```
{
    "startDate": "1994-10-10",
    "endDate": "1995-12-10",
    "Name": "Test Semester 2",
    "OrganizationID": 1
}
```

What is an Organization? You have to tell the frontend somehow what the current OrganizationID is
- [x] The endpoints that change or create data need to throw a 400/401 when correct data isn’t passed not just when the there is a mysql error on your side (i.e. the /update/password endpoint should 401 when the wrong old password is given etc.)
- [x] When there is a MySQL error you should console log the error and the endpoint it corresponds to because you are getting MySQL errors on the test server causing the server to crash and need to be restarted.

**Comment by cga101** [comment]
We're going to drop Organization from the current implementation, as I think it's supposed to be a field for  multiple schools (which would currently be out of scope).

There's a Google Doc that contains our db schema for testing/improvements that reflects these changes.

As of 3/22, the following still need changes : 
CreateSemester - Assigned to Cesar
Endpoint Validation - Cesar, Hira, and Myself
Console.Log - Cesar, Hira, and Myself

**Comment by cesarl88** [comment]
PUT /update/password
Tested working

 PUT /update/email
Tested working

 GET /generalUser/:userid
{
  "Error": false,
  "Message": "Success",
  "User": [
    {
      "FirstName": "Christian",
      "LastName": "Alexander",
      "UserType": "Student",
      "Email": "cga4@njit.edu"
    }
  ]
}

 POST /login
{
  "Error": false,
  "Message": "Success",
  "UserID": 3
}

 POST /CreateCourse : tries to set a column (Tittle) that doesn’t exist
Tested working
{
  "result": [
    {
      "LAST_INSERT_ID()": 5
    }
  ]
}

 POST /CreateSemester :
{
  "SemesterID": 6
}
